name: spotify_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter


  firebase_storage: ^12.2.0

  cupertino_icons: ^1.0.8
  flutter_svg:
  flutter_bloc:
  hydrated_bloc: ^9.0.0
  path_provider:
  firebase_core:
  firebase_auth:
  get_it:
  dartz:
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0
  google_fonts: ^6.2.1
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satoshi
      fonts:
       - asset: assets/fonts/Satoshi-Black.ttf
         weight: 900
       - asset: assets/fonts/Satoshi-Bold.ttf
         weight: 600
       - asset: assets/fonts/Satoshi-Medium.ttf
         weight: 500
       - asset: assets/fonts/Satoshi-Regular.ttf
         weight: 400
       - asset: assets/fonts/Satoshi-Light.ttf
         weight: 300


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
