// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1g6iri-LlIqJLRBLvMdv_FYiH773cTO4',
    appId: '1:731362356598:web:3fc40c1eb30a83ab795e57',
    messagingSenderId: '731362356598',
    projectId: 'spotifyclone0102',
    authDomain: 'spotifyclone0102.firebaseapp.com',
    storageBucket: 'spotifyclone0102.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChAukco6fZoITqa3lavNMUi6d3OKD5OG0',
    appId: '1:731362356598:android:0a13e058af1a75a7795e57',
    messagingSenderId: '731362356598',
    projectId: 'spotifyclone0102',
    storageBucket: 'spotifyclone0102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5NPHsjLT5_KWF2lpdPtN1mkyQfCHUAII',
    appId: '1:731362356598:ios:2cd63ddee8729d54795e57',
    messagingSenderId: '731362356598',
    projectId: 'spotifyclone0102',
    storageBucket: 'spotifyclone0102.appspot.com',
    iosBundleId: 'com.spoti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5NPHsjLT5_KWF2lpdPtN1mkyQfCHUAII',
    appId: '1:731362356598:ios:2cd63ddee8729d54795e57',
    messagingSenderId: '731362356598',
    projectId: 'spotifyclone0102',
    storageBucket: 'spotifyclone0102.appspot.com',
    iosBundleId: 'com.spoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1g6iri-LlIqJLRBLvMdv_FYiH773cTO4',
    appId: '1:731362356598:web:04c1d7f7c31a3eb1795e57',
    messagingSenderId: '731362356598',
    projectId: 'spotifyclone0102',
    authDomain: 'spotifyclone0102.firebaseapp.com',
    storageBucket: 'spotifyclone0102.appspot.com',
  );
}
